#Kotlin
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
#Kotlin Compiler Daemon: Caps the background compiler at 3 GB. This process compiles all Kotlin/JVM and Android code.
kotlin.daemon.jvmargs=-Xmx2560M
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true
#Kotlin/Native Compiler & Linker: Prevents LLVM and the Native compiler from ballooning during tasks like :sync-engine:linkDebugTestLinuxX64.
kotlin.native.jvmArgs=-Xmx2g

#Gradle
#Daemon (Build Coordinator): Caps the main daemon at 4 GB. It parses the build graph, tracks configuration caches, and manages workers.
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.configuration-cache=true
org.gradle.caching=true

#Concurrent Execution
#Allows Gradle to schedule :server:test and :app:test at the same time.
#But defines max tasks to run at once (e.g. Worker 1 runs :server:test, Worker 2 runs :app:test)
org.gradle.workers.max=3
org.gradle.parallel=true


#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

MOCHAME_KEYSTORE_PATH=/home/oscarmichael/secure-keys/mochame-release.jks
MOCHAME_KEYSTORE_PASSWORD=LeedsKotlin26!!
MOCHAME_KEY_ALIAS=mochame
MOCHAME_KEY_PASSWORD=LeedsKotlin26!!