package com.mochame.sync.api.network

/**
 * Client-side transport for sync communication.
 */
interface SyncTransport {
    /**
     * Returns true if the WebSocket session is active and open for transmission.
     */
    val isConnected: Boolean
    suspend fun connect(config: NetworkConfig)

    /**
     * Dispatches an upstream client to the sync relay.
     *
     * @param batchId Monotonically increasing client identifier generated by the client, necessary on Ack.
     * @param payload Serialized data.
     * @return [SendResult] describing whether the frame was dispatched, failed, or blocked by connection loss.
     */
    suspend fun send(batchId: Long, payload: ByteArray): SendResult

    suspend fun pause()
    suspend fun resume()

    /**
     * Registers a handler for inbound batch acknowledgements.
     */
    fun registerInboundAckHandler(onAck: suspend (Long, Long) -> Unit)
    /**
     * Registers a handler for incoming sync deltas.
     */
    fun registerInboundDeltaHandler(onReceived: suspend (Long, ByteArray) -> Unit)
    /**
     * Registers a callback invoked after the relay completes initial backfill.
     */
    fun setOnConnectedListener(onConnected: suspend () -> Unit)
    /**
     * Registers a callback invoked whenever the socket disconnects.
     */
    fun setOnDisconnectedListener(onDisconnected: suspend () -> Unit)
}

sealed interface SendResult {
    data object Success : SendResult
    data object NoConnection : SendResult
    data class Failure(val cause: Throwable) : SendResult
}

